name: minesweeper_game
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  shared_preferences: ^2.3.4
  custom_navigation_bar: ^0.8.2
  animated_notch_bottom_bar: ^1.0.3
  clay_containers: ^0.3.4
  audioplayers: ^6.1.0
  firebase_core: ^3.9.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/
