// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOnt-j1ffNUJRSa5VwaDMO087jEXhHfQY',
    appId: '1:248901197805:android:8a9d1bcbbe6812796891e4',
    messagingSenderId: '248901197805',
    projectId: 'reverseminesweeper',
    storageBucket: 'reverseminesweeper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApz_kTdCJ9JII5kwHPxamZ8t-eE7ZuiIo',
    appId: '1:248901197805:ios:3ffa609943585fd96891e4',
    messagingSenderId: '248901197805',
    projectId: 'reverseminesweeper',
    storageBucket: 'reverseminesweeper.firebasestorage.app',
    androidClientId: '248901197805-i45ephusoq81tpb89pt9vnv4eh4mbtt6.apps.googleusercontent.com',
    iosClientId: '248901197805-498136387elskped6djolu6gmv8p7usi.apps.googleusercontent.com',
    iosBundleId: 'com.example.minesweeperGame',
  );
}
